"use strict";

// CN=CLASS NAME
// F=FLIPKART
// FD=FIELD

const nykaatext = {
  N_LOAD_CHECKFORMAT_CN: "button.load-more-button",
  N_LOAD_NYKAAURL_CN: "div.css-8u7lru>a",
  N_PRODUCTNAME_CN: "div.css-1d5wdox>h1.css-1gc4x7i",
  N_PRODUCTLINK_CN: "div#product-list-wrap>div.productWrapper.css-xin9gt",
  N_PRICE_CN: "div.css-1d0jf8e>span.css-1jczs19",
  N_MAXRETAILPRICE_CN: "div.css-1d0jf8e>span.css-u05rr>span",
  N_IMAGELINK_CN: "div.css-5n0nl4>div>img",
  N_RATINGS_CN: "div.css-1hvvm95",
  N_DIFFRATINGS_CN: "div.css-kxc9rx>span",
  N_STARS_CN: "div.css-m6n3ou",
  N_LISTOFCATEGORIES_CN: "div.css-16kpx0l>ul.css-1uxnb1o>li",
  N_CATEGORY_CN: "a.name",
  N_REVIEWSLINK_CN: "div.css-1ux41ja>a.css-1xv8iu0",
  N_NUMBEROFIMAGES_CN: "div.css-qb9x9j",
  N_REVIEWS_CN: "div.css-z7l7ua",
  N_REVIEWS_TITLE_CN: "h4.css-tm4hnq",
  N_REVIEWS_SUMMARY_CN: "p.css-1n0nrdk",
  N_DISCOUNT_CN: "div.css-1d0jf8e>span.css-bhhehx",
  N_POSLINK_CN: "div.css-16kpx0l>ul.css-1uxnb1o>li.last-list.css-hnjjmz>a.name",
  N_POSITION_NAMES_CN: "div.css-1rd7vky>div.css-xrzmfa",
  N_PRODUCTNAME_FD: "ProductName",
  N_IMAGELINK_FD: "Imagelink",
  N_PRICE_FD: "Price",
  N_PRICE_PER_UNIT_FD: "Price_Per_Unit",
  N_MAXRETAILPRICE_FD: "Max_Retail_Price",
  N_RATINGS_FD: "Ratings",
  N_REVIEWS_FD: "Reviews",
  N_STARS_FD: "Stars",
  N_MOTHER_CATEGORY_FD: "Mother_Category",
  N_CATEGORY_FD: "Category",
  N_SUB_CATEGORY_FD: "Sub_Category",
  N_REVIEWSLINK_FD: "reviewsLink",
  N_NUMBEROFIMAGES_FD: "Number_Of_Images",
  N_DISCOUNT_FD: "Discount%",
  N_PRODUCT_FD: "Product",
  F_BRAND_FD: "Brand",
  N_STARRATINGS_FD: "Star_Ratings",
  N_SELLERDETAILS_FD: "SellerDetails",
  N_PLATFORM_FD: "Platform",
  N_NET_RATING_SCORE_FD: "Net_Rating_Score_NRS",
  N_TITLE_LENGTH_FD: "Title_Length",
  N_SEARCH_TERM_FD: "Search_Term",
  N_POSITION_FD: "Position",
  N_DATE_FD: "Date",
  N_QUANTITY_FD: "Quantity",
  N_QUANTITY_UNIT_FD: "Quantity_Unit",
  N_PRICE_PER_UNIT_FD: "Price_Per_Unit",
  N_MOST_USEFUL_FD: "MOST_USEFUL",
  N_MOST_POSITIVE_FD: "POSITIVE_FIRST",
  N_MOST_NEGATIVE_FD: "NEGATIVE_FIRST",
  N_POSLINK_FD: "posLink",
  NYKAA_PAGE_LINK: "https://www.nykaa.com",
};

module.exports = nykaatext;
