"use strict";

// CN=CLASS NAME
// F=FLIPKART
// FD=FIELD

const flipkarttext = {
  F_PRODUCTNAME_CN:
    "div._1AtVbE.col-12-12>div.aMaAEs>div>h1.yhB1nd>span.B_NuCI",
  F_PRICE_CN: "div._30jeq3._16Jk6d",
  F_MAXRETAILPRICE_CN: "div._3I9_wc._2p6lqe",
  F_IMAGELINK_CN: "div.CXW8mj._3nMexc>img",
  F_IMAGELINK_ALTERNATIVE_CN: "img._2r_T1I._396QI4",
  F_RATINGS_CN: "span._2_R_DZ._2IRzS8",
  F_RATINGS_ALTERNATIVE_CN: "div.row._2afbiS>div.col-12-12>span",
  F_STARS_CN: "div._3LWZlK._138NNC",
  F_STARS_ALTERNATIVE_CN: "div._2d4LTz",
  F_LISTOFCATEGORIES_CN: "div._1MR4o5>div._3GIHBu",
  F_CATEGORY_CN: "a._2whKao",
  F_REVIEWSLINK_CN: "div.col.JOpGWq>a",
  F_PRODUCTDETAILS1_CN: "div._2418kt>ul>li._21Ahn-",
  F_PRODUCTDETAILS2_CN: "table._14cfVK>tbody>tr._1s_Smc.row",
  F_PRODUCTDETAILS_KEY_CN: "td._1hKmbr.col.col-3-12",
  F_PRODUCTDETAILS_VALUE_CN: "li._21lJbe",
  F_SELLERLINK_CN: "li._38I6QT>a",
  F_DESCRIPTION_CN: "div._1mXcCf",
  F_NUMBEROFIMAGES_CN: "li._20Gt85._1Y_A6W",
  F_ALLRATINGS_CN: "div._13sFCC.miQW6D>ul._36LmXx>li._28Xb_u>div._1uJVNT",
  F_REVIEWS_CN: "div._1AtVbE>div._27M-vq>div.col>div.col._2wzgFH.K0kLPL",
  F_REVIEWS_TITLE_CN: "p._2-N8zT",
  F_REVIEWS_SUMMARY_CN: "div.t-ZTKy>div>div",
  F_SELLERS_CN: "div._2Y3EWJ",
  F_SELLERSNAME_CN: "div._3enH42>span",
  F_SELLERSRATINGS_CN: "div._3LWZlK._2GCNvL",
  F_SELLERSPRICE_CN: "div._25b18c>div._30jeq3",
  F_SELLERSFLIPKARTASSURED_CN: "div._3J2v2E>div>img",
  F_ADS_CN: "div._2tfzpE>span",
  F_PRODUCTNAME_FD: "ProductName",
  F_PRICE_FD: "Price",
  F_MAXRETAILPRICE_FD: "Max_Retail_Price",
  F_IMAGELINK_FD: "Imagelink",
  F_RATINGS_FD: "Ratings",
  F_REVIEWS_FD: "Reviews",
  F_STARS_FD: "Stars",
  F_MOTHER_CATEGORY_FD: "Mother_Category",
  F_CATEGORY_FD: "Category",
  F_SUB_CATEGORY_FD: "Sub_Category",
  F_REVIEWSLINK_FD: "reviewsLink",
  F_HIGHLIGHTS_FD: "Highlights",
  F_SELLERLINK_FD: "sellerslink",
  F_DESCRIPTION_FD: "Description",
  F_NUMBEROFIMAGES_FD: "Number_Of_Images",
  F_NUMBEROFSELLERS_FD: "Number_Of_Sellers",
  F_DISCOUNT_FD: "Discount%",
  F_PRODUCT_FD: "Product",
  F_BRAND_FD: "Brand",
  F_STARRATINGS_FD: "Star_Ratings",
  F_SELLERDETAILS_FD: "SellerDetails",
  F_MAX_PRICE_FD: "Max_Price",
  F_MIN_PRICE_FD: "Min_Price",
  F_ST_DEV_PRICE_FD: "St_Dev_Price",
  F_PLATFORM_FD: "Platform",
  F_NET_RATING_SCORE_FD: "Net_Rating_Score_NRS",
  F_TITLE_LENGTH_FD: "Title_Length",
  F_DESCRIPTION_FD: "Description",
  F_DESCRIPTION_LENGTH_FD: "Description_Length",
  F_SEARCH_TERM_FD: "Search_Term",
  F_POSITION_FD: "Position",
  F_DATE_FD: "Date",
  F_QUANTITY_UNIT_FD: "Quantity_Unit",
  F_PRICE_PER_UNIT_FD: "Price_Per_Unit",
  F_POSITIVE_FIRST_FD: "POSITIVE_FIRST",
  F_NEGATIVE_FIRST_FD: "NEGATIVE_FIRST",
  FLIPKART_PAGE_LINK: "https://www.flipkart.com",
};

module.exports = flipkarttext;
