"use strict";
// In this file all the reusable code are put together so that they can be called as per need.

// Establishing the connection to database
const connection = require("../connection");

const axios = require("axios");

const save = async (obj) => {
  const response = await axios({
    method: "post",
    url: "https://www.publiqverse.io/version-62l7/api/1.1/obj/ProductCatalogue",
    data: obj,
  });

  let html = response.data;
  return html;
};

// headers to send with api request to sites to avoid blockage
const headers = {
  Accept:
    "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
  "Accept-Encoding": "gzip, deflate, br",
  "Accept-Language": "en-US,en;q=0.9,la;q=0.8",
  Host: "httpbin.org",
  "Sec-Ch-Ua":
    '"Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"',
  "Sec-Ch-Ua-Mobile": "?0",
  "Sec-Ch-Ua-Platform": '"Windows"',
  "Sec-Fetch-Dest": "document",
  "Sec-Fetch-Mode": "navigate",
  "Sec-Fetch-Site": "cross-site",
  "Sec-Fetch-User": "?1",
  "Upgrade-Insecure-Requests": "1",
  "User-Agent":
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
  "X-Amzn-Trace-Id": "Root=1-646baec9-23c65be55fbb54967e9160ef",
};

const allProducts =
  "div._1YokD2._2GoDe3>div._1YokD2._3Mn1Gg>div._1AtVbE.col-12-12>div._13oc-S>div";
const imglink = "img._396cs4";

// Types of rating we want to scrap
const typesOfRatings = ["POSITIVE_FIRST", "NEGATIVE_FIRST"];

//Order of fields we want in the final output
const fields = [
  "Imagelink",
  "Productlink",
  "Position",
  "Product",
  "ProductName",
  "Brand",
  "Price",
  "Price_Per_Unit",
  "Max_Retail_Price",
  "Stars",
  "Ratings",
  "Reviews",
  "Mother_Category",
  "Category",
  "Sub_Category",
  "Num_5_Star_Ratings",
  "Num_4_Star_Ratings",
  "Num_3_Star_Ratings",
  "Num_2_Star_Ratings",
  "Num_1_Star_Ratings",
  "Platform",
  "Quantity",
  "Quantity_Unit",
  "Number_Of_Sellers",
  "SellerDetails",
  "Description",
  "Number_Of_Images",
  "IsAds",
  "POSITIVE_FIRST",
  "NEGATIVE_FIRST",
  "Net_Rating_Score_NRS",
  "Discount%",
  "Search_Term",
  "Min_Price",
  "Max_Price",
  "St_Dev_Price",
  "Title_Length",
  "Description_Length",
  "Date",
  "MOST_USEFUL",
];

// function to convert the string into Number by removing the unwanted symbols.
const replce = (str) => {
  while (str.includes(",")) {
    str = str.replace(",", "");
  }
  while (str.includes("₹")) {
    str = str.replace("₹", "");
  }
  return Number(str);
};

// Saving the data to the flipkartdatabase
let nykaasql = async (listofproducts) => {
  // Inserting the data into database
  let Product =
    "INSERT INTO NYKAA_PRODUCT_TABLE (Imagelink,Productlink, Position,Product, ProductName , Brand , Price ,Price_Per_Unit, Max_Retail_Price , Stars, Ratings , Reviews , Mother_Category , Category ,Sub_Category,Num_1_Star_Ratings ,Num_2_Star_Ratings ,Num_3_Star_Ratings ,Num_4_Star_Ratings ,Num_5_Star_Ratings ,Platform,Quantity ,Quantity_Unit, Number_Of_Sellers , Description, Number_Of_Images ,IsAds,Net_Rating_Score_NRS, Discount ,Search_Term ,Min_Price , Max_Price , St_Dev_Price, Title_Length , Description_Length , Date) VALUES ?";

  let values = [];
  //Make an array of values:
  for (let i = 0; i < listofproducts.length; i++) {
    let keys = [];

    for (let value in listofproducts[i]) {
      keys.push(listofproducts[i][value]);
    }
    values.push(keys);
  }

  //Execute the SQL statement, with the value array:
  if (values.length > 0) {
    connection.query(Product, [values], function (err, result) {
      if (err) throw err;
      console.log("Number of reco rds inserted: " + result.affectedRows);
    });
  }
};

// brands for nykaa
const brands = [
  "Maybelline New York",
  "Lakme",
  "Nykaa Cosmetics",
  "M.A.C",
  "The Face Shop",
  "L'Oreal Paris",
  "Nykaa Naturals",
  "Biotique",
  "Huda Beauty",
  "Kama Ayurveda",
  "Innisfree",
  "The Body Shop",
  "18.21 Man Made",
  "18m32",
  "2.Oh",
  "23 Yards",
  "24 Mantra",
  "3003BC",
  "3INA",
  "4711",
  "5 Elements by Radhika Gupta",
  "7th Heaven",
  "90 Feet By Dharavi Market",
  "A Clutch Story",
  "A Fragrance Story",
  "A Modernica Naturalis",
  "A-Derma",
  "A'kin",
  "Aadiva",
  "AARAI",
  "Aaranyaa",
  "Aaruvi Ruchi Verma",
  "Aastey",
  "Abelino",
  "Abena",
  "Accessher",
  "Accessorize London",
  "Ace Nutrimony",
  "ACE THE SPACE",
  "Acne Squad",
  "Actifit",
  "Activ Beaute",
  "Adam Wulf",
  "Addery",
  "adidas",
  "adidas Originals",
  "Adigo",
  "Adira",
  "Aditya Ahuja",
  "Adorenite",
  "Aegte",
  "Aer",
  "Aesthetic Bodies",
  "Affaires",
  "Aftershokz",
  "Afzal",
  "AG'S",
  "Agaro",
  "Ahilya Jewels",
  "Aigner",
  "Airwick",
  "Ajmal India",
  "Akiva",
  "Alainne",
  "Alan Truman",
  "ALANNA",
  "Alcove",
  "Aldo",
  "Aleva Naturals",
  "Alexandre Christie",
  "Alexandre. J",
  "ALFAPARF MILANO",
  "ALiX AViEN PARIS",
  "All Good Scents",
  "Allen Cooper",
  "Allen Solly",
  "Allin Exporters",
  "Allure",
  "ALMO",
  "Aloe Veda",
  "Alpecin",
  "Alpha Male",
  "Alphavedic",
  "Alpino",
  "Alvaro Castagnino",
  "Alyssa Ashley",
  "amag Beauty",
  "Amalfiee Ceramics",
  "Amaltaas",
  "Amante",
  "Amaya Decors",
  "Amazfit",
  "AMAzing EARTH",
  "Amazon",
  "Amazon Series",
  "Amazonas",
  "Amberry",
  "Ambi Pur",
  "Ambrane",
  "Ame",
  "American Eagle",
  "Aminu",
  "Amour",
  "Amrutam",
  "AMYRA",
  "Anastasia Beverly Hills",
  "Ancient Flower",
  "Ancient Living",
  "And Also",
  "AND Fragrances",
  "Andis",
  "andMe",
  "Andreas Osten",
  "Anekaant",
  "Ang-Tatva",
  "Angeline",
  "Anika's Creations",
  "Anne Klein",
  "Anomaly",
  "Ansell",
  "Anthi",
  "Antonio Banderas",
  "Antony Morato",
  "ANUVA",
  "Anveya",
  "AOMIDORI SHIMAI",
  "AQFIT",
  "Aqualogica",
  "aquawhite",
  "Aramis",
  "Aramusk",
  "Arata",
  "Aravi Organic",
  "Archies",
  "Arendelle",
  "Aretto",
  "Arganicare",
  "Argatin",
  "Arias",
  "Ariel",
  "Aries Gold",
  "Aris",
  "Ariul",
  "ARMAF",
  "ARMANI EXCHANGE",
  "Aroma Magic",
  "Aroma Treasures",
  "AromaMusk",
  "ART & PARFUM",
  "Artemis",
  "Artifice",
  "Artsy Design Co.",
  "Aryanveda",
  "As-It-Is Nutrition",
  "asa",
  "Ashpveda",
  "Asics",
  "Asmitta",
  "Assemblage",
  "Assembly",
  "Astaberry",
  "Astrid",
  "At Home by Nilkamal",
  "ATOPALM",
  "Atulya",
  "Auli",
  "AuraVedic",
  "Aureana",
  "Auric",
  "Aveda",
  "Aveeno",
  "Avene",
  "AVI LIVING",
  "AVI-8",
  "Avimee Herbal",
  "Avnii Organics",
  "Axe",
  "Axiom",
  "AY",
  "AYA",
  "Ayesha",
  "AyouthVeda",
  "Ayuga",
  "AYUTTVA",
  "Azafran",
  "Azah",
  "Azai by Nykaa Fashion",
  "Azani",
  "Azani Active Care",
  "Aztec Secret",
  "b.box",
  "Babila",
  "Baby Alive",
  "Baby Moo",
  "BabyChakra",
  "Babyliss",
  "Babymama",
  "BadgePack Designs",
  "Bag of Small Things",
  "Baggit",
  "Bagsy Malone",
  "Baidyanath",
  "Baise Gaba",
  "Bajaj",
  "Balenzia",
  "Bambo Nature",
  "Banjara's",
  "Bansri",
  "Barbie",
  "Bare Anatomy",
  "Bare Body Essentials",
  "Bare Body Plus",
  "Bare Essentials",
  "Barsano",
  "Basicare",
  "Bata",
  "Bath & Body Works",
  "Bathla",
  "Batiste",
  "Baylis & Harding",
  "BBETTER",
  "BBlunt",
  "BCBGMAXAZRIA",
  "Be Bodywise",
  "BE SOULFULL",
  "Be The Skin",
  "Be The Viraa",
  "Beardhood",
  "Beardo",
  "Beauprty",
  "Beautiliss",
  "Beauty of Joseon",
  "Beauty People",
  "Beautywise",
  "Bebe Nature",
  "Beco",
  "Beebaby",
  "Beeone",
  "BEL AVENIR",
  "belif",
  "Bella",
  "Bella Vita Organic",
  "Bella Voste",
  "Belleven",
  "Belleziya",
  "Bellofox",
  "Belora",
  "Below The Belt",
  "Ben Sherman",
  "Benefit Cosmetics",
  "Bentley",
  "Bentodent",
  "beplain",
  "Berdoues",
  "Bergner",
  "Berina",
  "Berry’s Intimatess",
  "Bespoke London",
  "Best Life",
  "Better Body Bombay",
  "Betty Barclay",
  "Beurer",
  "Beverly Hills Polo Club",
  "bFIT",
  "bGREEN",
  "BH Cosmetics",
  "Bharat & Dorris",
  "Bhu Botanicals",
  "BIANCA",
  "Bibado",
  "BiE - Beauty In Everything",
  "Bigen",
  "Bigflex",
  "Bijoux By Priya Chandna",
  "Biker's",
  "BILLI",
  "Biluma",
  "Bio Oil",
  "Bio-essence",
  "Biobloom",
  "Bioblush",
  "Biocule",
  "Bioderma",
  "Bionova",
  "Biore",
  "Biosilk",
  "Biosoft",
  "Biotique",
  "Biotique Natural Makeup",
  "Biotop Professional",
  "Bipha Ayurveda",
  "Birkenstock",
  "Black+Decker",
  "Blackmores",
  "Blank Slate Home",
  "Blaupunkt",
  "Blenior",
  "Bliscent",
  "Bliss Of Earth",
  "Blissclub",
  "Bloomsberry",
  "BLOOVS SPORTS",
  "Blue Heaven",
  "Blue Nectar",
  "Blueberry",
  "Blush9 Maternity",
  "BlushBee Beauty",
  "BMW",
  "boAt",
  "Bobbi Brown",
  "Body & Fragrance",
  "Body Code",
  "Body Cupid",
  "Body Fantasies",
  "Body Smith",
  "Bodycare",
  "BodyFirst",
  "Bodyguard",
  "BodyHerbals",
  "BODYX",
  "Bohemia Crystal",
  "Boho Botanist",
  "Bold Care",
  "Boldfit",
  "BOLON",
  "Bombae",
  "Bombay Shaving Company",
  "Bon Organics",
  "Bonayu",
  "Bonhomie",
  "Bonjour",
  "Bontress",
  "Boroplus",
  "Bose",
  "Boss",
  "Botanic Love",
  "BOTNAL",
  "Bottega Di Lungavita",
  "Boucheron",
  "Boujee Beauty",
  "BOULEVARD",
  "Boult Audio",
  "Bowtoes",
  "Brabantia",
  "Bralux",
  "Braun",
  "BRAVE ESSENTIALS",
  "Brick Brown",
  "Brillare",
  "Brinton",
  "Bronson Professional",
  "Brown Bear",
  "BrownSkin Beauty",
  "Brut",
  "Bruun & Stengade Accessories",
  "Brwn",
  "BRYAN & CANDY",
  "BSN",
  "BTN",
  "Buds & Berries",
  "Bulchee",
  "Bummer",
  "Burberry",
  "Burleigh",
  "Buti Pure",
  "Butter London",
  "Butterflies",
  "BVLGARI",
  "By Nature",
  "By Terry",
  "BySak",
  "C.A.L Los Angeles",
  "C2P Pro",
  "C9 Airwear",
  "CADIVEU",
  "Caim by Arelang",
  "Calcimax",
  "Callesta",
  "Calvadoss",
  "Calvin Klein",
  "Calvin Klein Sunglasses",
  "Calvin Klein Watches",
  "Campus",
  "Candyskin",
  "Caprese",
  "Captain Zack",
  "Caran D'Ache",
  "Carbamide Forte",
  "Carefree",
  "Caresmith",
  "Carlton London",
  "Carlton London Perfume",
  "Carlton London Watches",
  "Carmesi",
  "Carolina Herrera",
  "Carolina Herrera Fashion",
  "CARPISA",
  "CARRERA",
  "Carrera Sunglasses",
  "Carven",
  "CasaGold",
  "Case-Mate",
  "Casio",
  "Casmara",
  "CAT",
  "CATWALK",
  "Caudalie",
  "CAVIAR OF SWITZERLAND",
  "Celimax",
  "Ceriz",
  "Cerruti 1881",
  "Cetaphil",
  "CGG Cosmetics",
  "Chambor",
  "Chandrika",
  "Character",
  "Charlotte Raffaelli",
  "Charlotte Tilbury",
  "Charmacy Milano",
  "Charmis",
  "Chemist at Play",
  "Chemistry",
  "Cheryl's Cosmeceuticals",
  "Chicco",
  "Chicnutrix",
  "Chik",
  "Chilli Beans",
  "CHKOKKO",
  "Chloé",
  "Choko",
  "Chopard",
  "Chris Adams",
  "Chrysante",
  "Chumbak",
  "Chupps",
  "Ciaté London",
  "Ciel",
  "Cif",
  "CIGA DESIGN",
  "CINEMA SECRETS",
  "Cinthol",
  "Citizen",
  "CLARA",
  "Claude Bernard",
  "CLAY CRAFT",
  "Claymint",
  "Clean & Clear",
  "Clean & Dry",
  "Cleansense",
  "Clensta",
  "Clinic Plus",
  "Clinique",
  "Close-Up",
  "Closet Code",
  "Clotche",
  "Clovia",
  "Clt.s",
  "Club R",
  "Coach",
  "Coach Watches",
  "Coco Roots",
  "Coco Soul",
  "Cocomo",
  "Colab",
  "Colgate",
  "Color Chemistry",
  "Color Fx",
  "Colorbar",
  "Coloressence",
  "ColorPlay",
  "ColorSoul",
  "Colour Me",
  "Comfort",
  "CONCOCTED",
  "Conscious Chemist",
  "Core & Pure",
  "Core Asana",
  "CORE Designed by SPACES",
  "Corioliss",
  "Corseca",
  "Cos-IQ",
  "Cosa Nostraa",
  "Cosco",
  "Cosmetica",
  "COSMETOFOOD",
  "Cosmic Byte",
  "Cosmos by Bewakoof",
  "COSRX",
  "Courtyard",
  "Crazy Color",
  "Crazy Corner",
  "Crazy Owl",
  "Crennovations",
  "Crocs",
  "Cross",
  "Crossbeats",
  "Crossloop",
  "Crown",
  "Crusset",
  "CSC",
  "Cukoo",
  "Cultsport",
  "Curae Health",
  "Curio Cottage",
  "Curl Up",
  "Curlin",
  "Curlvana",
  "Curwish",
  "CXL",
  "D'chica",
  "D'SIGNER",
  "d'you",
  "D1 Milano",
  "Da Intimo",
  "Dabur",
  "Dafni",
  "Daily Life Forever52",
  "Daily Rituals",
  "DailyObjects",
  "Daisy Dixon",
  "Daniel Klein",
  "Daniel Wellington",
  "Danish Design",
  "Dartington",
  "DASTOOR",
  "Daughter Earth",
  "David Beckham",
  "David Jones",
  "Davidoff",
  "DAX",
  "Dazller Eterna",
  "DDecor Live Beautiful",
  "De Fabulous",
  "DearPacker",
  "Debasreee",
  "DeBelle",
  "Debon Herbals",
  "Deborah",
  "DECIWOOD",
  "Deconstruct",
  "DecorTwist",
  "Delon",
  "Denim",
  "Denman",
  "Denver",
  "Derma E",
  "Derma Essentia",
  "Dermacol",
  "Dermafique",
  "Dermalogica",
  "Dermatouch",
  "Dermawear",
  "Designbox",
  "Dettol",
  "Devano",
  "Deve Herbes",
  "Dexe",
  "Dhathri",
  "DHC Beauty",
  "Dhwani Bansal",
  "Diana Korr",
  "Dicora Urban Fit",
  "Diego dalla Palma Milano",
  "Diesel Sunglasses",
  "Digital Dress Room",
  "DIOR",
  "Dirty Works",
  "Disguise Cosmetics",
  "Diva Divine",
  "Divas Mantra",
  "Divine Aroma",
  "Diwaah",
  "Diya Aswani",
  "DKNY",
  "DoggyMan",
  "Dolce & Gabbana",
  "Don't Call Me Princess",
  "DOOBNOOB",
  "Doodle Collection",
  "Dorall Collection",
  "Dot & Key",
  "Dove",
  "DoYou",
  "Dr Oracle",
  "Dr. Morepen",
  "Dr. Odin",
  "Dr. Ortho",
  "Dr. Sheth's",
  "Dr. Vaidya's",
  "Dr. Vranjes Firenze",
  "Dr.Batra's",
  "Dr.Foot",
  "dr.organic",
  "Drape In Vogue",
  "Dreams",
  "Dromen & Co",
  "DSquared2",
  "Ducati Eyewear",
  "Ducati Watches",
  "Ducray",
  "Dugran By Dugristyle",
  "DukieKooky",
  "Dunhill",
  "Durex",
  "Duxot",
  "Dyna",
  "Dynamocks",
  "Dyson",
  "e.l.f. Cosmetics",
  "E2O",
  "Earth Bags",
  "Earth Rhythm",
  "earthBaby",
  "EASTHIDE",
  "Eat Anytime",
  "Eazybee",
  "Eco Corner",
  "Ecoberry",
  "EcoRight",
  "ECOVANI",
  "eCraftIndia",
  "EFG Store",
  "EKSA",
  "Ekta",
  "El Clasico",
  "Elaa",
  "Elchim",
  "Elenblu",
  "Elephant",
  "Elina",
  "Elite Models",
  "Elitty",
  "Elizabeth Arden",
  "Elle 18",
  "Ellement Co.",
  "Ellementry",
  "Ellips",
  "Elovera",
  "Elvey Essentials",
  "Emami",
  "Emanuel Ungaro",
  "Embark",
  "Embryolisse",
  "Emilio Pucci",
  "Enamor",
  "Enchanteur",
  "Endura",
  "Energy Strings",
  "Enerzal",
  "Engage",
  "ENN",
  "Eno",
  "Enoki",
  "Enrico",
  "Episoft",
  "Equal",
  "Eridani",
  "Ermenegildo Zegna",
  "Esbeda",
  "Escada",
  "Eske",
  "Eske Paris",
  "ESPRIT Collection",
  "Essence",
  "Essentia Extracts",
  "Estee Lauder",
  "Estele",
  "Eternal Love",
  "Eternia",
  "Etsley",
  "ETUDE HOUSE",
  "Eufy",
  "EUME",
  "Evaflor",
  "EVAM",
  "EVE LOM",
  "EveCare",
  "EVERDION",
  "EverEve",
  "Everpure Life",
  "Everteen",
  "Everyuth Naturals",
  "Evexpert",
  "EVOQ",
  "ExclusiveLane",
  "eyda",
  "Eyetex Dazller",
  "Eylina",
  "Eylure",
  "Faaya Gifting",
  "FabAlley",
  "Fabbhue",
  "Fabindia",
  "Fabindia Fashion",
  "Fable & Mane",
  "Fablestreet",
  "Fabpad",
  "Fabskin",
  "Fabula",
  "Face Rituals",
  "Faces Canada",
  "Fade Out",
  "FAE Beauty",
  "Fair & Handsome",
  "Faire L'amour",
  "FAITH & PATIENCE",
  "FAMMEDI",
  "Farmacy Beauty",
  "Fasderma",
  "Fasense",
  "FASHION COLOUR",
  "Fast&Up",
  "Fastrack",
  "Fastrack Accessories",
  "Fastrack Watches",
  "FCUK Watches",
  "Feather",
  "Felli",
  "Fem",
  "FemiSafe",
  "FEMNMAS",
  "FERNWEH",
  "Ferosh",
  "Ferrari Mobile Cases",
  "Ferro",
  "Festina",
  "Fiama",
  "Fida",
  "FILA",
  "Filone",
  "Filtra",
  "Find Your Happy Place",
  "Fingers",
  "Fire-Boltt",
  "First Pet",
  "First Water",
  "Fisher Space",
  "Fiskars",
  "Fit Face",
  "Fitbit",
  "Fitspire",
  "Fix My Curls",
  "Fixderma",
  "Fixderma Cosmetic Laboratories",
  "Fizza",
  "Fizzy Fern",
  "Flawless",
  "Flawsome",
  "FLiX (Beetel)",
  "FLOH",
  "Floren",
  "Floret",
  "Flower Beauty",
  "Floyd",
  "FLYING BERRY",
  "FNS",
  "Focallure",
  "Fogg",
  "Follihair",
  "foodstrong",
  "Foot Fuel",
  "Footlogix",
  "Forbis",
  "FOREO",
  "Forest Essentials",
  "Forever New",
  "Fossil",
  "Fourwalls",
  "Foxtale",
  "Fragrance & Beyond",
  "Fran Wilson Moodmatcher",
  "Franck Olivier",
  "Free Authority",
  "FREECULTR",
  "Freedom Tree",
  "Freelance",
  "French Connection",
  "French Connection Sunglasses",
  "FRENCH ESSENCE",
  "French Factor",
  "FRSH",
  "Fujifilm",
  "Funky Maharani",
  "FUR JADEN",
  "Furla",
  "FURR",
  "Fuschia",
  "FYOLI",
  "GAIA Aromatherapy",
  "Gajra Gang by Nykaa Fashion",
  "Gala of London",
  "GameSir",
  "GANS",
  "Gant",
  "GAP Fashion",
  "Garden Essentials",
  "Garmin",
  "Garnier",
  "GAT",
  "Gatsby",
  "Gauri International",
  "Gc",
  "Gem Roller",
  "GEMBLUE BioCare",
  "GemStella",
  "Gemtherapy",
  "Gentlemen's Crew",
  "Geomag",
  "Getmecraft",
  "Ghar Soaps",
  "Giggles & Wiggles",
  "Gillette",
  "Gillette Venus",
  "Ginni Filaments",
  "Gio Collection",
  "Giordano",
  "Giorgio Armani",
  "Giovanni",
  "GIVA",
  "Givenchy",
  "Gizga",
  "Gizmore",
  "GK Hair",
  "GLAM21",
  "GlamGals",
  "Glamina",
  "GlamPalm",
  "Glamveda",
  "GLASSLOCK",
  "Global Beauty Secrets",
  "Global Desi Perfume",
  "Globus Naturals",
  "Globus Remedies",
  "GLOOT",
  "Glow & Lovely",
  "GlowCollagen",
  "GlowGlutathione",
  "Glucon D",
  "GlutaGlow",
  "Glutaweis",
  "Glutone",
  "GM",
  "GNC",
  "GNIST",
  "Go Colors",
  "Godrej Anoop",
  "Godrej Expert",
  "Godrej Ezee",
  "Godrej No.1",
  "Godrej Nupur",
  "Godrej Professional",
  "Godrej Protekt",
  "GODS",
  "Goldprash",
  "Goli Nutrition",
  "Good knight",
  "Goodbye Gravity",
  "goodnessme",
  "GoPro",
  "Gorgias London",
  "Gorgio Professional",
  "Gorgy",
  "Gossip",
  "Goya Basics",
  "Graceful",
  "GREEN AND BEIGE",
  "Greenberry Organics",
  "Greenbrrew",
  "Greenviv",
  "GRIPP",
  "Gritzo",
  "Groomd",
  "Groomiist",
  "Groversons Paris Beauty",
  "GUBB",
  "Gucci",
  "Guerlain",
  "Guess",
  "Guess Bags",
  "Guess Sunglasses",
  "Guess Watches",
  "Gush Beauty",
  "Guysome",
  "GynoCup",
  "Gynoveda",
  "HabereIndia",
  "Hair & Care",
  "Hair Drama Company",
  "Hair Food",
  "HAIR4REAL",
  "Hair4U",
  "Hairmac",
  "Haironic",
  "HairPro",
  "HairTronic",
  "Hajamat",
  "Half N Half",
  "Hamdard",
  "HAMELIN",
  "HAMMER",
  "Hamster London",
  "Happier",
  "Happilo",
  "Harold Meagan",
  "Harpic",
  "Hasbro Gaming",
  "Havaianas",
  "Havells",
  "Hawkins & Brimble",
  "HE",
  "Head & Shoulders",
  "Heads Up For Tails",
  "Health Veda Organics",
  "HealthKart",
  "HealthSense",
  "HealthVit",
  "HealthViva",
  "Healthy Treat",
  "HealthyHey",
  "Hector Professional",
  "Heel & Buckle London",
  "Heelium",
  "Heka",
  "Helix",
  "Hem",
  "Hera",
  "Herbal Essences",
  "Herbal Hills",
  "Herbal Me",
  "HERMES",
  "Heyday",
  "Hi Life",
  "Hidesign",
  "HiLEDER",
  "HILO Design",
  "Himaira",
  "Himalaya",
  "Himalayan Organics",
  "Himani",
  "Hiphop",
  "Hipster",
  "HITKARI POTTERIES",
  "HNK",
  "Holistic India",
  "Hollyhock",
  "HomeTown",
  "Honeybee",
  "Honeybud",
  "HORRA",
  "HotIce",
  "House of Aroma",
  "House Of Beauty",
  "House of Makeup",
  "Huda Beauty",
  "Huggies",
  "Hugo Boss",
  "Hugo Boss Accessories",
  "Human+Kind",
  "Hummel",
  "Hungama Hilife",
  "Hydes N Hues",
  "HydraGlow",
  "Hygee",
  "Hype",
  "I AM EYECONIC",
  "I AM LOVE",
  "I KALL",
  "I-Feel",
  "Iba",
  "Ice-Watch",
  "ICHKAN",
  "ICONIC London",
  "IDEE",
  "iGRiD",
  "Ikiriya",
  "Ikkai by Lotus Herbals",
  "Ikonic Luxure",
  "Ikonic Professional",
  "Ilana",
  "ilearnngrow",
  "Iluvia",
  "IMAGE",
  "IMARS FASHION",
  "Imbue",
  "Immunace",
  "ImPower",
  "Inalsa",
  "Inatur",
  "Inbase",
  "Inc.5",
  "INCHIS",
  "Incolor",
  "Indalo",
  "inde wild",
  "India Grooming Club",
  "Indian Crystal Company",
  "Indica",
  "Indigifts",
  "Indulekha",
  "Indulgeo Essentials",
  "Indus Valley",
  "Infinity",
  "Inflame",
  "Infuzze",
  "Inglot",
  "Inhouse by Maspar",
  "Inja",
  "Inlife",
  "Inner Sense",
  "Innisfree",
  "Insight Cosmetics",
  "Insight Professional",
  "Instyle",
  "Intellilens",
  "Intimus",
  "Inveda",
  "INVU Fashion",
  "IÓ",
  "IORA",
  "IRIS COSMETICS",
  "IRTH",
  "IRUS",
  "ISDIN",
  "Ishhaara",
  "Isopure",
  "Issey Miyake",
  "It's Skin",
  "Ital Veloce",
  "Italwax",
  "IYKYK by Nykaa Fashion",
  "J. By Janvier",
  "Jack & Jones",
  "Jacques Bogart",
  "Jacques Du Manoir",
  "Jaguar",
  "Jaipur Kurti",
  "Jaipur Rugs",
  "Jaipur Watch Company",
  "James Bond 007",
  "Jaquline USA",
  "JBL",
  "JCPL",
  "Jean Paul Gaultier",
  "Jeanne Arthes",
  "Jeffree Star Cosmetics",
  "Jekyll & Hide",
  "Jena",
  "Jergens",
  "Jeva",
  "Jewels Galaxy",
  "Jimmy Choo",
  "Jiva Ayurveda",
  "Jo Malone London",
  "Jockey",
  "Jockey Juniors",
  "Jockey Man",
  "John Jacobs",
  "John's",
  "Johnson's",
  "Johori",
  "Jointace C2",
  "Joker & Witch",
  "Jolen New York",
  "Joseph Joseph",
  "Joules By Radhika",
  "Jovees",
  "Joy",
  "Juice To Cleanse",
  "Juicy Chemistry",
  "Juliet",
  "Juliette has a gun",
  "July",
  "Junghans",
  "Just Cavalli",
  "Just Herbs",
  "Just Jack",
  "Justanned",
  "K-Veda",
  "K.P. Namboodiri's",
  "Kaefie",
  "Kai",
  "Kairali",
  "Kaiv",
  "KAL HANS NATURALS",
  "Kama Ayurveda",
  "KamaSutra",
  "KANELLE Fragrances",
  "Kanvin",
  "Kapiva Ayurveda",
  "Kara",
  "Karatcart",
  "Karma Kettle",
  "Kastiya Jewels",
  "Kate Spade",
  "Kay Beauty",
  "Kaya",
  "Kaya Youth",
  "Kayali",
  "Kayos",
  "Kazarmaa",
  "Kazo",
  "Kelesta",
  "Ken Hom",
  "Kenkoh",
  "Kenneth Cole Accessories",
  "Kenneth Cole Sunglasses",
  "Kenneth Cole Watches",
  "Kent",
  "Kenzo",
  "Kerala Ayurveda",
  "Keshking",
  "Ketofy",
  "Kevin.Murphy",
  "Keya Seth",
  "Khaabka",
  "Khadi Natural",
  "Khadi Organique",
  "Khari Foods",
  "Khushi Jewels",
  "Kica",
  "Kicks and Crawl",
  "Kidsville",
  "Kiehl's",
  "Kiko Milano",
  "Kilner",
  "KimiNo",
  "Kimirica",
  "Kin Cosmetics",
  "Kingdom Of Lashes",
  "Kiri Kiri",
  "KIRO",
  "KIS",
  "KitchenCraft",
  "Klairs",
  "KLAVUU",
  "KleenOWipe",
  "KLEIO",
  "KLENVOR",
  "Kleral",
  "KLF Nirmal",
  "KLISSAA",
  "Kobra Labs",
  "KOCOSTAR",
  "Komli",
  "Kompanero",
  "Koparo",
  "Kora Organics",
  "Koric",
  "KOSCH ELEMENTE",
  "Kotex",
  "KRAFTPRO",
  "Kredo",
  "Kreo",
  "Krishna's Herbal & Ayurveda",
  "Kryolan",
  "Kryptic",
  "KT Professional",
  "Ktein",
  "KUBRA",
  "Kundan",
  "KYOCERA",
  "Kzen Skincare",
  "L.A. Colors",
  "L.A. Girl",
  "L'Action Paris",
  "L'Occitane",
  "L'Oreal Paris",
  "L'Oreal Professionnel",
  "La Cafetiere",
  "La Cremerie",
  "La Dimora Selections",
  "La Flora Organics",
  "La French",
  "La Mior",
  "La Shield",
  "La Vie En Rose",
  "Label Ritu Kumar",
  "Lacoste",
  "Lacoste Sunglasses",
  "Lacoste Watches",
  "Lacto Calamine",
  "LaFille",
  "LAFZ",
  "Laida",
  "LAIQA",
  "Lakme",
  "Lalique",
  "Lamuse",
  "Lancome",
  "LANEIGE",
  "Lanvin",
  "Lapis Bard",
  "Lapis O Lupo",
  "Lass Naturals",
  "Lattafa",
  "Lavie",
  "LAVOS",
  "Layer'r",
  "Layers",
  "LAZY BUMS",
  "LBEE",
  "Le Bois",
  "Le Marbelle",
  "Leading Lady",
  "Leaf",
  "Leather World",
  "Legal Bribe",
  "LEGO",
  "Lemme Be",
  "Lenora",
  "Lenovo",
  "Lenphor",
  "Lenskart Blu",
  "LetsShave",
  "Leuchtturm1917",
  "Lever Ayush",
  "Levi's",
  "Life & Pursuits",
  "Lifebuoy",
  "Lifelong",
  "LIGHT UP",
  "Likha by Nykaa Fashion",
  "Lil Ballerina",
  "Lil' Star by Ayesha",
  "Lilly & Sparkle",
  "Lim & Cello",
  "Lime Crime",
  "LINDBERGH",
  "Lino Perros",
  "Liril",
  "LISEN",
  "Listerine",
  "Little Hip Boutique",
  "Little Rawr",
  "Little's",
  "Littmuss",
  "Livia",
  "Living With Elan",
  "Livinguard",
  "Livon",
  "Lizol",
  "Lock & Lock",
  "Lockpin",
  "Logitech",
  "Lokait",
  "Lola's Closet",
  "Lolita Lempicka",
  "LOMANI",
  "London Pottery",
  "London Pride Cosmetics",
  "London Rag",
  "Lottie London",
  "Lotus Botanicals",
  "Lotus Herbals",
  "Lotus Make Up",
  "Lotus Organics",
  "Louis Philippe",
  "Love Beauty & Planet",
  "Love Earth",
  "Love Organically",
  "LoveChild Masaba",
  "Luciara",
  "Lumiford",
  "Luminox",
  "Lux",
  "LuxaDerme",
  "LUXIE",
  "Luxuri",
  "LUXURIATE",
  "Lyla Blanc",
  "LYN",
  "Lyra",
  "M.A.C",
  "Maate",
  "Macadamia",
  "Machismo",
  "mackly",
  "Macmerise",
  "MADES",
  "MAGNEQ",
  "Maisha",
  "Majestic Perfume",
  "Majestique",
  "Makclan",
  "MAKE UP FOR EVER",
  "MAKEUP BY SITI",
  "Makeup Eraser",
  "Makeup Revolution",
  "Malibu",
  "Mamaearth",
  "Mamaxpert",
  "MamyPoko",
  "Man Arden",
  "Man Matters",
  "Mana Ayurvedam",
  "ManCode",
  "Manestream",
  "Manforce",
  "Manic Panic",
  "Manor House",
  "ManSure",
  "Mantra Herbal",
  "Marc Anthony",
  "Marc Jacobs",
  "Marie Claire Fashion",
  "Mario Badescu",
  "Marjo Eyewear",
  "Marks & Spencer",
  "MARS",
  "Mars by GHC",
  "Marshall",
  "Maryaj",
  "Masculine",
  "Maserati",
  "Masilo",
  "Mason Home",
  "Maspar",
  "MASTER & DYNAMIC",
  "Mathey-Tissot",
  "Matra",
  "Matrix",
  "Matt look",
  "Mauri Herbal",
  "Max Care",
  "Max Factor",
  "Maybelline New York",
  "MAYZE",
  "MBOSS",
  "MCaffeine",
  "Medela",
  "Mederma",
  "Medimix",
  "Medion Healthcare",
  "Mee Mee",
  "Meera",
  "Megaga",
  "Meistersinger",
  "Melblok",
  "MELBON",
  "Melissa",
  "mellow",
  "Melomane",
  "Memumi",
  "MEN DESERVE",
  "Menopace Iso",
  "MensXP MUD",
  "Mercedes-Benz",
  "Merit",
  "Merlion Naturals",
  "MESMARA",
  "MESMERRO",
  "Mettle",
  "MevoFit",
  "Mi",
  "MIAH Decor",
  "Michael Kors",
  "Michelle Alexander",
  "Micromax",
  "Mikasa",
  "Milagro Beauty",
  "Milani",
  "Milano Treasures",
  "Mindware",
  "MINI",
  "Minimalist",
  "Ministry of Nuts",
  "Miniware",
  "MINIX",
  "Mint & Oak",
  "Mirabelle",
  "MIRACLE DIGITAL",
  "MIRAGGIO",
  "Mirah Belle",
  "Miri",
  "MISA",
  "Miscellanea",
  "Miss Claire",
  "Miss Rose",
  "Missha",
  "Missoni",
  "Missoni Fashion",
  "Mitali Jain",
  "Mivi",
  "MIXT by Nykaa Fashion",
  "Mizon",
  "MNSH",
  "Mocemsa",
  "Mod & Shy",
  "Mode By Red Tape",
  "Modern Myth",
  "Modisch",
  "Moedbuille",
  "Moha",
  "Moi",
  "Mojo Bar",
  "MOLESKINE",
  "Mollismoons ",
  "Mom & World",
  "MomLyf",
  "Mommypure",
  "Momsoon",
  "Mond'Sub",
  "Mondaine",
  "Monno",
  "Monopoly",
  "Monrow",
  "Mont Blanc Eyewear",
  "Montblanc",
  "Moody",
  "Moon Rabbit",
  "Moov",
  "Morisons Baby Dreams",
  "Moroccanoil",
  "Morph Maternity",
  "MORPHE",
  "Morpheme Remedies",
  "Moschino",
  "Moskito Safe",
  "Mother Sparsh",
  "Mothercare",
  "Mountainor",
  "Movado",
  "Moveda",
  "Mr. Barber",
  "MUA",
  "Mueras",
  "Mukti Gold",
  "Murad",
  "Muscle Monk",
  "Muscle Torque",
  "MuscleBlaze",
  "MusclePharm",
  "MuscleTech",
  "MuscleXP",
  "Mustela",
  "Muuchstac",
  "Muvazo",
  "MVMT",
  "MVYNO",
  "myDaily",
  "MyFitFuel",
  "MyFitness",
  "MyGlamm",
  "Mylo Care",
  "Mylo Veda",
  "MyMuse",
  "MYPRO SPORT NUTRITION",
  "Myprotein",
  "Myra Veda",
  "Mystere Paris",
  "Mystic Valley",
  "Mystique Earth",
  "NA-KD",
  "Nabhi Sutra",
  "Nacific",
  "Nair",
  "NAKPRO",
  "Nakshikathaa",
  "Namhya Foods",
  "Namyaa",
  "NAPA HIDE",
  "Narciso Rodriguez",
  "NARUMI",
  "Nat Habit",
  "Natio",
  "Natural Vibes",
  "Naturali",
  "Naturalizer",
  "Nature Protect",
  "Nature Sure",
  "Nature Trail",
  "Nature's Essence",
  "Nature's Island",
  "Nature's Nest",
  "Nature's Touch",
  "Naturigin",
  "Natyv Soul",
  "Naughty Girl",
  "Nautica",
  "Nautica Accessories",
  "Nautica Candles",
  "Nautica Sunglasses",
  "Navratna",
  "NEA",
  "NeceSera",
  "Nectar Valley",
  "Neelamari Herbs",
  "Neemans",
  "Neemli Naturals",
  "Nejo",
  "Neko",
  "NEOGEN DERMALOGY",
  "Neolayr",
  "Neud",
  "Neuherbs",
  "Neulife",
  "Neurozan",
  "Neutrogena",
  "New NB",
  "NEWD",
  "NEWISH",
  "Newnik",
  "NEWSHA",
  "NEXT2SKIN",
  "NEYAH",
  "NFI Essentials",
  "Niana",
  "Nicka K",
  "Niconi",
  "Niine",
  "Nike",
  "Nimwash",
  "Nina Ricci",
  "Ningen",
  "Nirvasa",
  "Niscka",
  "Nite Flite",
  "Nivea",
  "NMFe",
  "Nobile 1942",
  "Noise",
  "NOOD",
  "Noosh",
  "Nordgreen",
  "Noritake",
  "North Star",
  "NoStrain",
  "Note",
  "Nourish Mantra",
  "Nourish Vitals",
  "Nouriza",
  "Nova",
  "Novo Koyo",
  "Nua",
  "Nudestix",
  "Nudge",
  "Nuerma Science",
  "NUI",
  "NUMI",
  "Nurturing Green",
  "Nusuk",
  "Nutrabay",
  "Nutrafirst",
  "Nutrainix",
  "Nutrela",
  "Nutribears",
  "Nutricook",
  "NutriGlow",
  "Nutrinorm",
  "Nutriorg",
  "NutriOrro",
  "Nutrisharks",
  "NutritJet",
  "NutroActive",
  "Nutty Yogi",
  "Nuutjob",
  "NUXE",
  "Nyassa",
  "Nykaa Cosmetics",
  "Nykaa Fashion",
  "Nykaa Naturals",
  "Nykaa Pro Essentials",
  "Nykaa SKINRX",
  "Nykd by Nykaa",
  "Nyle",
  "Nyor",
  "Nyumi",
  "NYVEDA",
  "NYX Professional Makeup",
  "O-Lens",
  "O.B.",
  "O.P.I",
  "O3+",
  "O4U",
  "Oakley",
  "Oateo",
  "Obaku",
  "Oberglas",
  "OBSESSIONS",
  "Ocean Professional",
  "OCEANIDES",
  "ODEON",
  "Odette",
  "Odiva",
  "Odonil",
  "OFRA",
  "OGX",
  "Ohria Ayurveda",
  "Olaiva",
  "Olamor",
  "Olaplex",
  "Olay",
  "Old Spice",
  "Olena",
  "Oleum Cottage",
  "Olivia",
  "Omega",
  "OMORFEE",
  "ONE THING",
  "One8 by Virat Kohli",
  "OneLife",
  "OneOdio",
  "Onikuma",
  "Online Quality Store",
  "ONLY",
  "Onzyme",
  "OOMPH",
  "Open Secret",
  "Opium Eyewear",
  "OPPO",
  "Optimum Nutrition",
  "Ora d'oro Beauty",
  "Oraimo",
  "Oral-B",
  "Orange Tree",
  "OrangeDaily",
  "Orchard Toys",
  "Organi Vibe",
  "Organic Harvest",
  "Organic India",
  "Organic Kitchen",
  "Organic Works",
  "Orgera",
  "Oriental Botanics",
  "Origami",
  "Ornate Jewels",
  "Oscar",
  "Oshea Herbals",
  "Osmo",
  "Osteocare",
  "Otoori",
  "OTT SKYNCARE",
  "OUI&ME",
  "OUTBACK",
  "Ovation",
  "Ovego",
  "Oxi9",
  "OXO",
  "Oxyglow Herbals",
  "OxyLife",
  "Oziva",
  "Ozomax",
  "Ozone",
  "Ozuko",
  "Paaduks",
  "PAC",
  "Paco Rabanne",
  "Paese Cosmetics",
  "Pahadi Local",
  "Palladio",
  "Palmer's",
  "Palmolive",
  "Palmonas",
  "Pampers",
  "Pan Aromas",
  "Panache",
  "PANASH",
  "Panasonic",
  "Panchamrit",
  "Panchvati Herbals",
  "Pantene",
  "Papa Pawsome",
  "Parachute",
  "Paradyes",
  "Paree",
  "Parfait",
  "PARIM",
  "Park Avenue",
  "Passion Indulge",
  "PAT McGRATH LABS",
  "PAUL HEWITT",
  "Paul Mitchell",
  "Paul Penders",
  "Pawsh",
  "Peaceable Kingdom",
  "Pears",
  "Pebble",
  "Pedigree",
  "Pee Safe",
  "Peebuddy",
  "Pegasus",
  "Pennline",
  "Peora",
  "Pepe Jeans",
  "Pepe Jeans Eyewear",
  "Pepsodent",
  "Perca",
  "PERCLUTION ENTERPRISE",
  "Perenne",
  "Perfectil",
  "Perfora",
  "Perfume Lounge",
  "Perfumers Choice",
  "Perron Rigot",
  "Personic",
  "Petal Fresh",
  "Peter England",
  "Peter England Fragrances",
  "Peter Minuit",
  "Petitfee",
  "Philip B",
  "Philips",
  "Philips Audio",
  "Philips Home",
  "Phy",
  "Physicians Formula",
  "Physiogel",
  "Pick Pocket",
  "Pierre Cardin",
  "Pierre Cardin Bags",
  "Pierre Cardin Paris",
  "Pigeon",
  "Pigment Play",
  "Pilgrim",
  "Pink Woolf",
  "Pinky Goat",
  "Pinnacle",
  "PINQ",
  "Pipa Bella by Nykaa Fashion",
  "Pippin Paris",
  "PIU",
  "PIXI",
  "Plan B",
  "PLANTAS",
  "PLAY",
  "Play-Doh",
  "Playboy",
  "Playskool",
  "Plextone",
  "Plix",
  "Plum",
  "Plush",
  "PMD Beauty",
  "PodSquad",
  "Polaroid",
  "Police",
  "Police Sunglasses",
  "Police Watches",
  "Pollution Free by Guudcure",
  "Ponds",
  "Poo-De-Cologne",
  "Popcorn Games & Puzzles",
  "PopSockets",
  "Porsche",
  "Portronics",
  "Postcard",
  "Power",
  "Power Gummies",
  "Praakritik",
  "Praavy",
  "Praccessorii",
  "Prakriti Herbals",
  "Prakrta",
  "Praush",
  "PRAVO",
  "Preethi",
  "Pregnacare",
  "Premsons",
  "PrettyCat",
  "Priveda",
  "Priyaasi",
  "Pro Arte",
  "Pro Nature",
  "Profusion Cosmetics",
  "Prolixr",
  "PROMEN",
  "Protouch",
  "Provoc",
  "PROWOMEN",
  "pTron",
  "Pucelle",
  "Pulp",
  "Puma",
  "Puma Sunglasses",
  "PunnkFunnk",
  "Purayati",
  "Pure Cure + Co.",
  "Pure Home + Living",
  "Pure Nutrition",
  "Purecon",
  "PureSense",
  "Puressentiel",
  "Puretta",
  "Purna",
  "Q-Sera",
  "QAADU",
  "Qaaleen",
  "QCY",
  "Qiwion",
  "QOD Professional",
  "Qraa",
  "Qraa Men",
  "Quantum",
  "Quarantine",
  "Queen Be",
  "Quench Botanics",
  "Qurez",
  "Quttos",
  "Raaga Professional",
  "Rabitat",
  "RADHIKA AGRAWAL JEWELS",
  "Radhikas",
  "Radox",
  "RAEGR",
  "Rag & Co",
  "Raho Safe",
  "Rahul Phate's",
  "Rajasthan Decor",
  "Ramsons",
  "Rapoo",
  "RAS Luxury Oils",
  "Rasasi",
  "Rashki",
  "RAVE",
  "Ray-Ban",
  "Raymond",
  "Raymond Fragrances",
  "Re'equil",
  "Reaction Kenneth Cole",
  "Real Barrier",
  "Real Techniques",
  "Realme",
  "Recode",
  "Red Hunt",
  "Red Tape",
  "Red Tape Accessories",
  "Reebok",
  "Reebok Classics",
  "Reeshape",
  "Refresh Botanicals",
  "REGROWZ",
  "Rejuvenating UBTAN",
  "Relispray",
  "Remington",
  "Remove",
  "Rene Furterer",
  "Renee Cosmetics",
  "Repêchage",
  "Replay",
  "Reverzo",
  "Revlon",
  "Revolution Haircare",
  "Revolution Pro",
  "Rexona",
  "Rey Naturals",
  "Rhe Cosmetics",
  "Rhea Jewellery",
  "Rica",
  "Richfeel",
  "Ridacne",
  "RiiFFS",
  "Rimmel London",
  "Rin",
  "RiteBite Max Protein",
  "Riti",
  "Ritu Kumar",
  "Rivela",
  "Riyo Herbs",
  "Roberto Cavalli",
  "Roberto Cavalli by Frank Muller",
  "Roberto Cavalli Watches",
  "Rodania",
  "Roja Parfums",
  "Rome",
  "Ronnie Coleman",
  "Roop Mantra",
  "Root Deep",
  "Root7",
  "Roots",
  "Roots & Herbs",
  "Rosemoore",
  "Rostaa",
  "Rotary",
  "Rovectin",
  "Royal Mirage",
  "Royal Son",
  "ROZANA by ZARIIN",
  "Rozia",
  "RSVP By Nykaa Fashion",
  "RUBY RAANG STUDIO",
  "Ruby's Organics",
  "Rude Cosmetics",
  "Rufa Beauty",
  "Rugberry",
  "Runmus",
  "Runway Ritual",
  "Rustic Art",
  "S.Oliver",
  "Saba",
  "Sacred Salts",
  "SADHEV",
  "Saffola FITTIFY",
  "SAFYR",
  "Sally Hansen",
  "Salon In A Box",
  "SALT.",
  "Salvatore Ferragamo",
  "Samourai",
  "Sampan",
  "Samsonite",
  "Samsung",
  "San Calpa",
  "SANCTUS",
  "Sandak",
  "SanDisk",
  "SandPuppy",
  "Sanfe",
  "Sanity",
  "Sanjeev Kapoor",
  "SanNap",
  "Santa Barbara Polo & Racquet Club",
  "Santoor",
  "Saphed",
  "Sapper",
  "Sara",
  "Saraf RS Jewellery",
  "Saregama",
  "SASHA",
  "Satthwa",
  "Saturday Skin",
  "Savlon",
  "Scalpe Pro",
  "Scalppie",
  "Scentio",
  "SCENTRA",
  "Scholl Fashion",
  "Schwarzkopf",
  "Schwarzkopf Professional",
  "SCOOBIES",
  "SCOTCH & SODA",
  "Scott Sunglasses",
  "Scuderia Ferrari",
  "Seagate",
  "SeaSoul",
  "Sebamed",
  "Sebastian Professional",
  "Secret Alchemist",
  "Secret Temptation",
  "Secret Wish",
  "Secrets By ZeroKaata",
  "Secrett Curves",
  "Secrid",
  "Seer Secrets",
  "SeeSee",
  "SEEVO",
  "SEIKO",
  "Seki Edge",
  "Selsun",
  "Sensodyne",
  "SERY",
  "SESA",
  "Set Wet",
  "Setu",
  "SHADES OF LIFE",
  "Shahnaz Husain",
  "Shakira",
  "Shankara",
  "SHARP",
  "Shaya by CaratLane",
  "Shaze",
  "Sheaffer",
  "Sheba",
  "Sheer by Priyaasi",
  "Sheneed",
  "Sherrif Shoes",
  "Shesha Ayurveda",
  "Shiseido",
  "Shoetopia",
  "Shopaarel",
  "Shopbloom",
  "SHOSHAA",
  "SHOWOFF",
  "Shure",
  "SHUZ TOUCH",
  "Shyaway",
  "Siddhayu",
  "Sigma Beauty",
  "Signaxo",
  "Silkberry",
  "SilkTree",
  "Sillysally",
  "Silvermerc Designs",
  "Simple",
  "Simply Nam",
  "Simply Nutra",
  "Sirona",
  "Sivya by Home",
  "Six Pack Nutrition",
  "Skagen",
  "SKECHERS",
  "Skechers Sunglasses",
  "Skillmatics",
  "Skin Cottage",
  "Skin Elements",
  "Skin Fx",
  "Skin Pot Co",
  "Skin Secrets",
  "Skinfood",
  "Skinn and You",
  "Skinn By Titan",
  "SkinQ",
  "Skinvest",
  "Skip Hop",
  "Skivia",
  "SKOG",
  "Skore",
  "Skullcandy",
  "Skyn Organic Co.",
  "SKYNOPTIK",
  "Slazenger",
  "Sleek",
  "SlickFix",
  "Sloggi",
  "Slova",
  "Slumber Jill",
  "Smart Felt Toys",
  "Smart Greens",
  "Smartserve",
  "Smartsters",
  "Smashbox",
  "Smiley - Quick Dry",
  "SmiloShine",
  "Smith & Blake",
  "Smitten",
  "Smoothskin",
  "Smugglerz Inc",
  "Snake Brand",
  "Sneaker Lab",
  "SNP Prep",
  "So Fetch",
  "SO... Fragrance",
  "SockSoho",
  "Softsens",
  "Sofy",
  "Soho Boho Studio",
  "SOIE",
  "Sol de Janeiro",
  "Sole House",
  "SOME BY MI",
  "Sonari",
  "Sonata",
  "Sony",
  "Sorich Organics",
  "Sotrue",
  "Soulflower",
  "SoulTree",
  "Soundcore",
  "SOVA",
  "SP",
  "Spa Ceylon Luxury Ayurveda",
  "Spaces",
  "Spantra",
  "Spars",
  "Spawake",
  "Speedo",
  "Spekta Cosmetics",
  "Spiegelau",
  "Spiky",
  "Spinz",
  "Spiritual Warrior",
  "Spraymintt",
  "Spruce Shave Club",
  "Spykar",
  "Spykar Fragrance",
  "Squish Town",
  "Sri Jagdamba Pearls",
  "Sri Sri Tattva",
  "St. D'vencé",
  "St. Ives",
  "St.Botanica",
  "ST.JOHN Cobra",
  "Star Struck by Sunny Leone",
  "Stars Cosmetics",
  "Staunch",
  "Stayfree",
  "Stephen Joseph",
  "Stole & Yarn",
  "Stonesoup",
  "Strand by Obaku",
  "Streak Street",
  "Streax",
  "Streax Professional",
  "Street Wear",
  "Strokes by Namrata Mehta",
  "Studio Etheno",
  "Stuffcool",
  "Styli",
  "StylPro",
  "Suave Kids",
  "SUDBURY 1776",
  "Suganda",
  "SUGAR",
  "SUGAR POP",
  "SugarBear",
  "Sugarfree",
  "Suhani Pittie",
  "Sukkhi",
  "Sulwhasoo",
  "Summer",
  "SunScoop",
  "Sunsilk",
  "Suntique",
  "Super Smelly",
  "Superbottoms",
  "Superdrug",
  "Superdry",
  "Suprfit",
  "Surf Excel",
  "Surya Brasil",
  "svaa.life",
  "Svacch",
  "Swagme",
  "Swarovski Sunglasses",
  "Swati Cosmetics",
  "Swayam",
  "Swee",
  "Sweet Dreams",
  "Sweet Heart",
  "SWISNI",
  "Swiss Arabian",
  "Swiss Beauty",
  "Swiss Image",
  "Swiss Military",
  "Swiss Military Hanowa",
  "Swiss Soldiers",
  "Swisse",
  "Sylvi",
  "SYNAA",
  "Syoss",
  "Syrene",
  "SYSKA",
  "Syska Fashion",
  "TABAC",
  "TAC - The Ayurveda Co.",
  "Tampax",
  "Tangle Teezer",
  "Tann Trim",
  "Tansha Quo",
  "Tarini Nirula",
  "Tash Hair",
  "Tatha",
  "Tattvalogy",
  "Tea Culture of The World",
  "Tea Treasure",
  "Tea Trunk",
  "Teachers’ Grace",
  "Teakwood",
  "Teal & Terra",
  "Teal by CHUMBAK",
  "Ted Baker",
  "Ted Smith",
  "Teejh",
  "TEMPTU",
  "TGL Co.",
  "Thalgo",
  "Thank You Farmer",
  "That Sassy Thing",
  "The 7 DeKor",
  "The Artment",
  "The Bath Store",
  "The Beauty Co.",
  "The Beauty Sailor",
  "The Bling Girll",
  "The Body Care",
  "The Body Shop",
  "THE CAI STORE",
  "The Cosmetic Republic",
  "The Cutians",
  "The Dance Bible",
  "The Decor Mart",
  "The Decor Remedy",
  "The Derma Co",
  "The Earth Collective",
  "The Face Shop",
  "THE GUSTO",
  "The Healthy Company",
  "The Home Story",
  "The House Of Ganges",
  "The House of Trendz",
  "The Indie Earth",
  "The Jewel Factor",
  "The Kaftan Company",
  "THE LEATHER STORY",
  "The Love Co.",
  "The Madras Trunk",
  "The Man Company",
  "The Men's Lab",
  "The Moms Co.",
  "The Nature's Co.",
  "The Ordinary",
  "The Organic Forest",
  "The Pink Foundry",
  "The Pitara Project",
  "THE PONY & PEONY CO.",
  "The Pure Story",
  "The Purple Sack",
  "The Rolling Concept",
  "The Skin Co.",
  "THE SKIN DIET COMPANY",
  "The Skia Ayurveda",
  "Uppercase",
  "Upsilon",
  "Urban Botanics",
  "Urban Space",
  "Urban Veda",
  "Urbanears",
  "UrbanGabru",
  "UrbanYog",
  "URBO",
  "Uroparis",
  "Usher",
  "Ustraa",
  "UXR Bath & Body",
  "Vaadi Herbals",
  "Vahdam",
  "VAKU",
  "Van Heusen",
  "Van Heusen Woman Lingerie and Athleisure",
  "Vandelay",
  "Vanguard",
  "Vansaar",
  "VANSON",
  "Vaseline",
  "VAST",
  "Vasu",
  "Vasundhara",
  "Vatika",
  "VAUNT",
  "Vdesi",
  "VEA",
  "Veda Homes",
  "Vedaearth",
  "Vedagiri",
  "VEDAN",
  "Vedic Line",
  "Vedic Valley",
  "VedicRoots",
  "Vedix",
  "Veedaa",
  "Veet",
  "VEGA",
  "VEGA Professional",
  "Vegetal",
  "Velocity Eyewear",
  "Veloz",
  "Velvery",
  "Velvet By Night",
  "Velway",
  "Veoni Belle",
  "Verada Beauty",
  "Vero Moda Intimates",
  "Versace",
  "Versace Watches",
  "Versus",
  "Veruschka By Payal Kothari",
  "VERYMISS",
  "Vesca",
  "VGR",
  "VI-JOHN",
  "VI-JOHN Saffron",
  "Vichy",
  "Vicks",
  "Victoria's Secret",
  "Victoria's Secret Sunglasses",
  "Vidivi",
  "Vigini",
  "Vigneto",
  "Vilam",
  "Villain",
  "VILVAH",
  "Vim",
  "Vincent Chase",
  "Vinod",
  "Vintage Vistha",
  "VIRAASI",
  "Virtue",
  "Viseart",
  "Visual Echoes",
  "Vitamin C",
  "Vitress",
  "VitusFiz",
  "Vivel",
  "Vivinkaa",
  "VLCC",
  "VOESH",
  "Vogue Eyewear",
  "Volamena",
  "Voncasa",
  "Votre",
  "Voyage",
  "Vrinda",
  "VWash",
  "WAABI-SAABI",
  "Wacoal",
  "Wahey",
  "WAHL",
  "Waldon",
  "WallMantra",
  "Wanderlust",
  "WD",
  "Web Eyewear",
  "WeCool",
  "WeDo Professional",
  "Welhome",
  "Wella Professionals",
  "Wellbeing Nutrition",
  "Wellcore",
  "Wellman",
  "Wellwoman",
  "Welly",
  "Welspun",
  "West Coast",
  "Wet n Wild",
  "What's Up Wellness",
  "Whats Down",
  "Whiskas",
  "Whisper",
  "White Lies",
  "Wild Organic",
  "Wild Stone",
  "Wildcraft",
  "WILDHORN",
  "WILLOW & SMITH",
  "Wings",
  "Winston",
  "Wishcare",
  "Wishful",
  "Wishtel",
  "Wizer",
  "Wldflwr Ntrls",
  "Woke Nutrition",
  "WomanLikeU",
  "Wommune",
  "Wonderchef",
  "Wonderize",
  "WOW",
  "Wow Matcha",
  "Wurze",
  "XAKA",
  "Xante",
  "XLR8 Sports Nutrition",
  "XO Curls",
  "XTEP",
  "XX Revolution",
  "Xylys",
  "XYXX",
  "Yamamay",
  "Yankee Candle",
  "Yardley London",
  "Yelloe",
  "Yellow Chimes",
  "Yellow Marigold",
  "YouBella",
  "YourHappyLife",
  "Yves Rocher",
  "Yves Saint Laurent",
  "Zandu",
  "ZARIIN",
  "Zaveri Pearls",
  "Zavya",
  "Zebronics",
  "Zelena",
  "Zencia Beauty",
  "Zenvista",
  "Zeppelin",
  "ZeroKaata",
  "Zevic",
  "Zilch",
  "ZILVER",
  "Zingavita",
  "Zippo",
  "Zivame",
  "ZLADE",
  "ZM Zayn & Myza",
  "Zobha",
  "ZOE AYLA",
  "Zohra",
  "Zoli",
  "Zoook",
  "Zoop",
  "Zori World",
];

// Exporting all the fields so that they can be accessed from other files whenever neccessary
module.exports = {
  headers,
  allProducts,
  imglink,
  typesOfRatings,
  fields,
  replce,
  brands,
  nykaasql,
  save,
};
